// index.tsx
import Head from "next/head";
import { BaseLayout } from "./layouts/baseLayout";
import { api } from "~/utils/api";
import Link from "next/link";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Welcome to Cyber Tutor!</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <p>Select a topic from the menu.</p>
      </BaseLayout>
    </>
  );
}